# 1) คำสั่งใดใช้ติดตั้ง NumPy ในสภาพแวดล้อม Python ได้โดยตรง

In [15]:
# 1) คำสั่งใดใช้ติดตั้ง NumPy ในสภาพแวดล้อม Python ได้โดยตรง
! pip install numpy

# Ans B) pip install numpy

# 2) การนำเข้า NumPy ให้ใช้นามแฝงมาตรฐานว่า np ในข้อใด

In [6]:
# 2) การนำเข้า NumPy ให้ใช้นามแฝงมาตรฐานว่า np ในข้อใด
import numpy as np

# Ans C) import numpy as np

# 3) สำหรับอาเรย์ arr_2d = np.array([[1,5,2,0],[8,3,6,1],[1,7,2,9]]) ค่าของ arr_2d.shape คืออะไร

In [7]:
# 3) สำหรับอาเรย์ arr_2d = np.array([[1,5,2,0],[8,3,6,1],[1,7,2,9]]) ค่าของ arr_2d.shape คืออะไร
arr_2d = np.array([[1,5,2,0],[8,3,6,1],[1,7,2,9]])
print(arr_2d)

# Ans A) (4,3)	

[[1 5 2 0]
 [8 3 6 1]
 [1 7 2 9]]


# 4) ให้ default_array = np.array([1,2,3,4,5,6]) ผลของ default_array[:3] คือข้อใดต่อไปนี้

In [8]:
# 4) ให้ default_array = np.array([1,2,3,4,5,6]) ผลของ default_array[:3] คือข้อใดต่อไปนี้
default_array = np.array([1,2,3,4,5,6])
default_array[:3]

# Ans A) [1,2,3]

array([1, 2, 3])

# 5) จากข้อเดิม ผลของ default_array[3:] คือ

In [9]:
# 5) จากข้อเดิม ผลของ default_array[3:] คือ
default_array[3:]

# Ans C) [4,5,6]

array([4, 5, 6])

# 6) ให้ default_array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) ค่า default_array_2d[1,3] เท่ากับข้อใดต่อไปนี้

In [10]:
# 6) ให้ default_array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) ค่า default_array_2d[1,3] เท่ากับข้อใดต่อไปนี้
default_array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
default_array_2d[1,3]

# Ans C) 8

np.int64(8)

# 7) ให้ array_attribute = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) ค่าของ array_attribute.ndim คือข้อใดต่อไปนี้

In [11]:
# 7) ให้ array_attribute = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) ค่าของ array_attribute.ndim คือข้อใดต่อไปนี้
array_attribute = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array_attribute.ndim

# Ans B) 2 

2

# 8) จากอาเรย์เดียวกัน array_attribute.size มีค่าเท่าใด

In [12]:
# 8) จากอาเรย์เดียวกัน array_attribute.size มีค่าเท่าใด
array_attribute.size

# Ans C) 12 

12

# 9) คำสั่งใดสร้างอาเรย์เลขคี่จาก 1 ถึง 15 ได้ถูกต้อง

In [13]:
# 9) คำสั่งใดสร้างอาเรย์เลขคี่จาก 1 ถึง 15 ได้ถูกต้อง
np.arange(1,16,2)

# Ans A) np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# 10) np.arange(0,10,2) จะได้อาเรย์ยาวเท่าใด

In [14]:
# 10) np.arange(0,10,2) จะได้อาเรย์ยาวเท่าใด
np.arange(0,10,2)

# Ans B) 5

array([0, 2, 4, 6, 8])

# 11) np.linspace(0,1,5) ค่าองค์ประกอบลำดับที่ 3 (index 2) คือข้อใดต่อไปนี้

In [15]:
# 11) np.linspace(0,1,5) ค่าองค์ประกอบลำดับที่ 3 (index 2) คือข้อใดต่อไปนี้
np.linspace(0,1,5)

# Ans A) 0.25	

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 12) ข้อใด “ไม่ถูกต้อง” เกี่ยวกับฟังก์ชันสร้างอาเรย์

In [16]:
# 12) ข้อใด “ไม่ถูกต้อง” เกี่ยวกับฟังก์ชันสร้างอาเรย์
np.arrang(4) 

# Ans D) np.arrang(4) สร้างอาเรย์ 0..3

AttributeError: module 'numpy' has no attribute 'arrang'

# 13) ให้ b = np.array([[1,1],[2,2]]) ผลของ b.sum(axis=0) คือข้อใดต่อไปนี้ 

In [ ]:
# 13) ให้ b = np.array([[1,1],[2,2]]) ผลของ b.sum(axis=0) คือข้อใดต่อไปนี้ 
b = np.array([[1,1],[2,2]])
b.sum(axis=0)

# Ans B) [3,3]

array([3, 3])

# 14) ให้ arr = np.arange(12) ข้อใด “ถูกต้อง”

In [ ]:
# 14) ให้ arr = np.arange(12) ข้อใด “ถูกต้อง”
arr.reshape(6,2).T.shape == (2,6)	

# Ans C) arr.reshape(6,2).T.shape == (2,6)	

True

# 15) ให้ a = np.ones((2,2)), b = np.zeros((2,2)) ผลของ np.vstack((a,b)).shape คือข้อใดต่อไปนี้

In [ ]:
# 15) ให้ a = np.ones((2,2)), b = np.zeros((2,2)) ผลของ np.vstack((a,b)).shape คือข้อใดต่อไปนี้
a = np.ones((2,2)), 
b = np.zeros((2,2))
a,b.shape
# np.vstack((a,b)).shape

# Ans C) (2,2)	

((array([[1., 1.],
         [1., 1.]]),),
 (2, 2))

# 16) ให้ arr_split = np.arange(24).reshape(3,8) ผลของ np.hsplit(arr_split, 2) แต่ละชิ้นมี shape เป็นข้อใดต่อไปนี้ 

In [ ]:
# 16) ให้ arr_split = np.arange(24).reshape(3,8) ผลของ np.hsplit(arr_split, 2) แต่ละชิ้นมี shape เป็นข้อใดต่อไปนี้ 
arr_split = np.arange(24).reshape(3,8)
np.hsplit(arr_split, 2)

# Ans B) (3,4)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]])]

# 17) ให้ a = np.arange(6); b = a.view(); b[0] = 99 ค่าของ a[0] จะเป็นเท่าใด

In [ ]:
# 17) ให้ a = np.arange(6); b = a.view(); b[0] = 99 ค่าของ a[0] จะเป็นเท่าใด
a = np.arange(6); b = a.view(); b[0] = 99
a[0]

# Ans B) 99

np.int64(99)

# 18) ให้ arr = np.arange(12) ข้อใดตรงกับผล arr[[1,3,5]] 

In [ ]:
# 18) ให้ arr = np.arange(12) ข้อใดตรงกับผล arr[[1,3,5]] 
arr = np.arange(12)
arr[[1,3,5]] 

# Ans A) [1,3,5]

array([1, 3, 5])

# 19) ให้ arr = np.arange(12) ผลของ arr[arr > 5] คือข้อใดต่อไปนี้

In [ ]:
# 19) ให้ arr = np.arange(12) ผลของ arr[arr > 5] คือข้อใดต่อไปนี้
arr = np.arange(12)
arr[arr > 5]

# Ans A) [6,7,8,9,10,11]

array([ 6,  7,  8,  9, 10, 11])

# 20) ให้ data = np.array([1,2]), ones = np.ones(2) ผลของ data / ones คือข้อใดต่อไปนี้

In [ ]:
# 20) ให้ data = np.array([1,2]), ones = np.ones(2) ผลของ data / ones คือข้อใดต่อไปนี้
data = np.array([1,2]),
data 
# ones = np.ones(2)
# ones

# Ans B) [1.,2.]

(array([1, 2]),)

# 21) คำสั่งใดสร้าง DataFrame จากลิสต์ของลิสต์ได้ถูกต้อง

In [ ]:
# 21) คำสั่งใดสร้าง DataFrame จากลิสต์ของลิสต์ได้ถูกต้อง
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6]])
print(df)

# Ans B) pd.DataFrame([[1,2,3],[4,5,6]]) 	

   0  1  2
0  1  2  3
1  4  5  6


# 22) ต้องการกำหนดชื่อคอลัมน์เป็น ["A","B","C"] ตอนสร้าง DataFrame ใช้พารามิเตอร์ใด

In [ ]:
# 22) ต้องการกำหนดชื่อคอลัมน์เป็น ["A","B","C"] ตอนสร้าง DataFrame ใช้พารามิเตอร์ใด
names = ["A","B","C"] 

# Ans A) names = 

# 23) กำหนด index เองใน pd.DataFrame(..., index=[...]) มีผลอย่างไร

In [13]:
# 23) กำหนด index เองใน pd.DataFrame(..., index=[...]) มีผลอย่างไร
import pandas as pd

data = [[10, 20], [30, 40]]
df = pd.DataFrame(data, columns=['A','B'], index=['row1','row2'])
print(df)


# Ans C) เปลี่ยน label ของแถว 

       A   B
row1  10  20
row2  30  40


# 24) ฟังก์ชันใดใช้โหลดไฟล์ Excel

In [ ]:
# 24) ฟังก์ชันใดใช้โหลดไฟล์ Excel
import pandas as pd
df = pd.read_excel('data.xlsx')
print(df.head())

# Ans B) pd.read_excel() 

# 25) ข้อใดต่อไปนี้อ่านชีตชื่อ "Sheet2" จาก Excel 

In [ ]:
# 25) ข้อใดต่อไปนี้อ่านชีตชื่อ "Sheet2" จาก Excel 
pd.read_excel(p, sheet="Sheet2")

# Ans A) pd.read_excel(p, sheet="Sheet2")

# 26) โหลด CSV จาก URL เป็น orders

In [ ]:
# 26) โหลด CSV จาก URL เป็น orders
orders = pd.read_csv("http://...")
# Ans A) orders = pd.read_csv("http://...")

# 27) orders.info() ให้ข้อมูลหลักๆ อะไร

In [ ]:
# 27) orders.info() ให้ข้อมูลหลักๆ อะไร
import pandas as pd

data = {'A':[1,2,3], 'B':[4,5,None]}
df = pd.DataFrame(data)
df.info()

# Ans B) รายชื่อคอลัมน์, Non-Null Count, Dtype, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       3 non-null      int64  
 1   B       2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 180.0 bytes


# 28) ข้อใดต่อไปนี้เป็นวิธีดูรายชื่อคอลัมน์ทั้งหมดของ DataFrame ชื่อ orders

In [ ]:
# 28) ข้อใดต่อไปนี้เป็นวิธีดูรายชื่อคอลัมน์ทั้งหมดของ DataFrame ชื่อ orders
import pandas as pd

data = {'OrderID':[1,2], 'Product':['A','B']}
orders = pd.DataFrame(data)

print(orders.columns)
 

# Ans C) orders.columns 

Index(['OrderID', 'Product'], dtype='object')


# 29) ข้อใดต่อไปนี้เป็นการเลือกคอลัมน์เดียว Country จาก DataFrame ชื่อ orders

In [ ]:
# 29) ข้อใดต่อไปนี้เป็นการเลือกคอลัมน์เดียว Country จาก DataFrame ชื่อ orders
import pandas as pd
data = {'Country':['TH','US','JP'], 'Sales':[100,200,150]}
orders = pd.DataFrame(data)
print(orders["Country"])


# Ans B) orders["Country"]

0    TH
1    US
2    JP
Name: Country, dtype: object


# 30) ข้อใดคือการเลือกหลายคอลัมน์ ['Customer','Country']

In [ ]:
# 30) ข้อใดคือการเลือกหลายคอลัมน์ ['Customer','Country']
import pandas as pd
data = {'Customer':['A','B','C'], 'Country':['TH','US','JP'], 'Sales':[100,200,150]}
orders = pd.DataFrame(data)
print(orders[['Customer','Country']])

# Ans B) orders[['Customer','Country']]

  Customer Country
0        A      TH
1        B      US
2        C      JP


# 31) ข้อใดใช้ loc เลือกแถว 0–20 เฉพาะคอลัมน์ 'Category'

In [ ]:
# 31) ข้อใดใช้ loc เลือกแถว 0–20 เฉพาะคอลัมน์ 'Category'
import pandas as pd
data = {'Category':['A','B','C','D','E'], 'Sales':[100,200,150,120,130]}
orders = pd.DataFrame(data)
print(orders.loc[0:3, 'Category'])

# Ans B) orders.loc[0:20,'Category']

0    A
1    B
2    C
3    D
Name: Category, dtype: object


# 32) ข้อใดต่อไปนี้เลือกแถว 10–30 เฉพาะคอลัมน์ ['OrderID','Quantity','Price','Paid']

In [ ]:
# 32) ข้อใดต่อไปนี้เลือกแถว 10–30 เฉพาะคอลัมน์ ['OrderID','Quantity','Price','Paid']
import pandas as pd
data = {
    'OrderID': range(50),
    'Quantity': range(50,100),
    'Price': range(100,150),
    'Paid': ['Yes']*50,
    'Customer': ['A']*50
}
orders = pd.DataFrame(data)
subset = orders.loc[10:30, ['OrderID','Quantity','Price','Paid']]
print(subset)

# Ans B) orders.loc[10:30, ['OrderID','Quantity','Price','Paid']]

    OrderID  Quantity  Price Paid
10       10        60    110  Yes
11       11        61    111  Yes
12       12        62    112  Yes
13       13        63    113  Yes
14       14        64    114  Yes
15       15        65    115  Yes
16       16        66    116  Yes
17       17        67    117  Yes
18       18        68    118  Yes
19       19        69    119  Yes
20       20        70    120  Yes
21       21        71    121  Yes
22       22        72    122  Yes
23       23        73    123  Yes
24       24        74    124  Yes
25       25        75    125  Yes
26       26        76    126  Yes
27       27        77    127  Yes
28       28        78    128  Yes
29       29        79    129  Yes
30       30        80    130  Yes


# 33) ข้อใดต่อไปนี้กรองแถวที่ Quantity > 5 ให้ได้ DataFrame

In [23]:
# 33) ข้อใดต่อไปนี้กรองแถวที่ Quantity > 5 ให้ได้ DataFrame
import pandas as pd
data = {'OrderID':[1,2,3,4], 'Quantity':[3,6,2,8]}
orders = pd.DataFrame(data)
filtered = orders[orders["Quantity"] > 5]
print(filtered)

# Ans B) orders[orders["Quantity"] > 5]

   OrderID  Quantity
1        2         6
3        4         8


# 34) ข้อใดต่อไปนี้เป็นการใช้เงื่อนไขหลายเงื่อนไขที่แสดงถึง

In [24]:
# 34) ข้อใดต่อไปนี้เป็นการใช้เงื่อนไขหลายเงื่อนไขที่แสดงถึง
import pandas as pd
data = {'Quantity':[2,4,5], 'Country':['Thailand','Thailand','US']}
orders = pd.DataFrame(data)
filtered = orders[(orders["Quantity"] > 3) & (orders["Country"] == "Thailand")]
print(filtered)

# Ans B) orders[(orders["Quantity"] > 3) & (orders["Country"] == "Thailand")]

   Quantity   Country
1         4  Thailand


# 35) ข้อใดต่อไปนี้เป็นการใช้เงื่อนไขหลายเงื่อนไขที่แสดงถึงเงื่อนไข OR

In [25]:
# 35) ข้อใดต่อไปนี้เป็นการใช้เงื่อนไขหลายเงื่อนไขที่แสดงถึงเงื่อนไข OR
import pandas as pd
data = {
    'Category':['Electronics','Clothing','Electronics'],
    'Paid':['Yes','No','Yes']
}
orders = pd.DataFrame(data)
filtered = orders[(orders["Category"] == "Electronics") | (orders["Paid"] == "No")]
print(filtered)

# Ans  C) orders[(orders["Category"] == "Electronics") | (orders["Paid"] == "No")]

      Category Paid
0  Electronics  Yes
1     Clothing   No
2  Electronics  Yes


# 36) ข้อใดต่อไปนี้ใช้ isin: เลือกประเทศเฉพาะ ['Thailand','Japan','USA']

In [ ]:
# 36) ข้อใดต่อไปนี้ใช้ isin: เลือกประเทศเฉพาะ ['Thailand','Japan','USA']
import pandas as pd
data = {'Country':['Thailand','Japan','USA','UK']}
orders = pd.DataFrame(data)
filtered = orders[orders["Country"].isin(['Thailand','Japan','USA'])]
print(filtered)

# Ans B) orders[orders["Country"].isin(['Thailand','Japan','USA'])]

# 37) ข้อใดต่อไปนี้ใช้ query กรองออเดอร์หมวด Fashion และราคามากกว่า 1000

In [26]:
# 37) ข้อใดต่อไปนี้ใช้ query กรองออเดอร์หมวด Fashion และราคามากกว่า 1000
import pandas as pd
data = {'Category':['Fashion','Electronics','Fashion'],
        'Price':[1200,800,900]}
orders = pd.DataFrame(data)
filtered = orders.query("Category == 'Fashion' and Price > 1000")
print(filtered)

# Ans A) orders.query("Category == 'Fashion' and Price > 1000")

  Category  Price
0  Fashion   1200


# 38) ข้อใดต่อไปนี้เพิ่มคอลัมน์คงที่และคอลัมน์คำนวณ (เช่น Total = Quantity*Price)

In [27]:
# 38) ข้อใดต่อไปนี้เพิ่มคอลัมน์คงที่และคอลัมน์คำนวณ (เช่น Total = Quantity*Price)
import pandas as pd
data = {'Quantity':[2,3], 'Price':[100,200]}
orders = pd.DataFrame(data)
orders['Shop'] = 'Bangkok'
orders['Total'] = orders['Quantity'] * orders['Price']
print(orders)

# Ans A)
# orders['Shop'] = 'Bangkok'
# orders['Total'] = orders['Quantity'] * orders['Price']


   Quantity  Price     Shop  Total
0         2    100  Bangkok    200
1         3    200  Bangkok    600


# 39) ข้อใดต่อไปนี้เป็นการลบหลายคอลัมน์ด้วย drop 

In [28]:
# 39) ข้อใดต่อไปนี้เป็นการลบหลายคอลัมน์ด้วย drop 
import pandas as pd
data = {'Paid':[1,0], 'Category':['A','B'], 'Price':[100,200]}
orders = pd.DataFrame(data)
# ลบหลายคอลัมน์ และ assign ให้ตัวแปรใหม่
orders = orders.drop(columns=['Paid','Category'])
print(orders)

# Ans B) orders = orders.drop(columns=['Paid','Category'])

   Price
0    100
1    200


# 40) ข้อใดต่อไปนี้ เรียงลำดับตาม Country และรองลงมาด้วย Price จากน้อยไปมาก

In [29]:
# 40) ข้อใดต่อไปนี้ เรียงลำดับตาม Country และรองลงมาด้วย Price จากน้อยไปมาก
import pandas as pd
data = {'Country':['US','Thailand','US','Thailand'],
        'Price':[200,100,150,50]}
orders = pd.DataFrame(data)
sorted_orders = orders.sort_values(['Country','Price'], ascending=[True,True])
print(sorted_orders)

# Ans B) orders.sort_values(['Country','Price'], ascending=[True,True])

    Country  Price
3  Thailand     50
1  Thailand    100
2        US    150
0        US    200
