## k-NN

In [112]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split  # แบ่งข้อมูลเป็นชุดฝึกสอนและทดสอบ
from sklearn.neighbors import KNeighborsClassifier # นำเข้าโมเดล KNN
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # เมตริกสับสน , 

In [113]:
# การใช้งาน Machine Learning
data = pd.read_csv('./dataset/Iris.csv')  # แสดง 5 แถวแรก
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [114]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [115]:
# กำหนด x และ y (ทาเกตหรือสปีชี้)
X = data[[ "SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].values
y = data['Species']

In [116]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [117]:
X.shape

(150, 4)

In [118]:
# แบ่งชุดข้อมูลเป็นชุดฝึกสอน (80%) และชุดทดสอบ (20%)
# test_size= 0.2 หมายถึง 20% ของข้อมูลทั้งหมดจะถูกใช้เป็นชุดทดสอบ
# random_state= 42 ใช้เพื่อการแบ่งข้อมูลสามารถทำซ้ำได้
# X,y แบ่งข้อมูลคุณลักษณะและป้ายกำกับ

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 1 )
# tam = 2

In [119]:
X_train

array([[6.1, 3. , 4.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [5.6, 2.5, 3.9, 1.1],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2.8, 5.1, 2.4],
       [5.3, 3.7, 1.5, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [5.2, 3.4, 1.4, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3. , 5.5, 2.1],
       [5.1, 3.5, 1.4, 0.3],
       [6. , 2.2, 5. , 1.5],
       [6.3, 2.9, 5.6, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [7.7, 2.6, 6.9, 2.3],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [6.9, 3.1, 5.4, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 3.4, 4.5, 1.6],
       [7.7, 2.8, 6.7, 2. ],
       [5.7, 3. , 4.2, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3. , 1.4, 0.1],
       [4.7, 3

In [120]:
# เรียกใช้งาน โมเดล KNN 
knn_model = KNeighborsClassifier( n_neighbors = 5 )  # กำหนด K=3
# tam = 5

In [121]:
# สอน โมเดลด้วยชุดฝึกสอน // train the model with training set
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [122]:
# test the model with testning set
y_pred = knn_model.predict(X_test)

In [123]:
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [124]:
# ประเมินผลของโมเดลด้วยความแม่นยำ (Accuracy)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy*100)

100.0


In [125]:
Confusion_matx = confusion_matrix(y_test, y_pred)
print(Confusion_matx)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [ ]:
clf_report = classification_report(y_test, y_pred)
print(clf_report)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [1]:
# Sumary
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split  # แบ่งข้อมูลเป็นชุดฝึกสอนและทดสอบ
from sklearn.neighbors import KNeighborsClassifier # นำเข้าโมเดล KNN
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # เมตริกสับสน , 

# การใช้งาน Machine Learning
data = pd.read_csv('./dataset/Iris.csv')  # แสดง 5 แถวแรก
data.head()

data.info()

# กำหนด x และ y (ทาเกตหรือสปีชี้)
X = data[[ "SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].values
y = data['Species']

# แบ่งชุดข้อมูลเป็นชุดฝึกสอน (80%) และชุดทดสอบ (20%)
# test_size= 0.2 หมายถึง 20% ของข้อมูลทั้งหมดจะถูกใช้เป็นชุดทดสอบ
# random_state= 42 ใช้เพื่อการแบ่งข้อมูลสามารถทำซ้ำได้
# X,y แบ่งข้อมูลคุณลักษณะและป้ายกำกับ

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 1 )
# tam = 2

X_train

# เรียกใช้งาน โมเดล KNN 
knn_model = KNeighborsClassifier( n_neighbors = 5 )  # กำหนด K=3
# tam = 5

# สอน โมเดลด้วยชุดฝึกสอน // train the model with training set
knn_model.fit(X_train, y_train)

# test the model with testning set
y_pred = knn_model.predict(X_test)

y_pred

# ประเมินผลของโมเดลด้วยความแม่นยำ (Accuracy)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy*100)

Confusion_matx = confusion_matrix(y_test, y_pred)
print(Confusion_matx)

clf_report = classification_report(y_test, y_pred)
print(clf_report)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
100.0
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         6

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

