## kNN-wine

In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split  # แบ่งข้อมูลเป็นชุดฝึกสอนและทดสอบ
from sklearn.neighbors import KNeighborsClassifier # นำเข้าโมเดล KNN
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # เมตริกสับสน , 

In [2]:
# การใช้งาน Machine Learning
data = pd.read_csv('./dataset/winequality-red.csv')  # แสดง 5 แถวแรก
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
# กำหนด x และ y (ทาเกตหรือสปีชี้)
X = data[[ "fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]].values
y = data['quality']

In [6]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [8]:
X.shape

(1599, 11)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 1 )

In [10]:
X_train

array([[ 7.   ,  0.65 ,  0.02 , ...,  3.47 ,  0.67 ,  9.5  ],
       [10.2  ,  0.42 ,  0.57 , ...,  3.04 ,  0.63 ,  9.6  ],
       [ 5.2  ,  0.34 ,  0.   , ...,  3.68 ,  0.79 , 14.   ],
       ...,
       [ 6.6  ,  0.725,  0.09 , ...,  3.35 ,  0.49 , 10.8  ],
       [ 7.2  ,  0.63 ,  0.   , ...,  3.37 ,  0.58 ,  9.   ],
       [ 9.1  ,  0.4  ,  0.5  , ...,  3.21 ,  0.69 , 12.5  ]],
      shape=(1279, 11))

In [11]:
# เรียกใช้งาน โมเดล KNN 
knn_model = KNeighborsClassifier( n_neighbors = 5 )  # กำหนด K=3
# tam = 5

In [12]:
# สอน โมเดลด้วยชุดฝึกสอน // train the model with training set
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [13]:
# test the model with testning set
y_pred = knn_model.predict(X_test)

In [14]:
y_pred

array([5, 5, 7, 5, 6, 6, 6, 5, 7, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5,
       5, 6, 5, 5, 6, 5, 5, 5, 6, 7, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6,
       5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 7, 7, 6, 6, 5, 5, 5, 5, 5, 5, 5,
       6, 5, 5, 6, 5, 6, 5, 7, 7, 5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6,
       5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5,
       6, 5, 6, 6, 5, 7, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 7, 6, 5, 5,
       5, 5, 7, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5,
       6, 7, 6, 6, 6, 6, 7, 6, 5, 5, 5, 6, 5, 5, 5, 7, 6, 6, 5, 5, 7, 6,
       6, 5, 5, 6, 6, 7, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 5, 7, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5,
       5, 6, 5, 5, 5, 6, 6, 5, 7, 6, 4, 6, 7, 6, 5, 5, 7, 6, 6, 5, 5, 6,
       6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 7, 6, 5, 6,
       5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 7, 5, 7, 5, 6, 5, 5, 6,
       6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6,

In [15]:
# ประเมินผลของโมเดลด้วยความแม่นยำ (Accuracy)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy*100)

50.31250000000001


In [16]:
Confusion_matx = confusion_matrix(y_test, y_pred)
print(Confusion_matx)

[[ 0  0  0  1  0  0]
 [ 0  0  9  4  0  0]
 [ 0  0 95 40  5  0]
 [ 0  1 62 59 12  0]
 [ 0  0  7 16  7  0]
 [ 0  0  0  1  1  0]]


In [17]:
clf_report = classification_report(y_test, y_pred)
print(clf_report)

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        13
           5       0.55      0.68      0.61       140
           6       0.49      0.44      0.46       134
           7       0.28      0.23      0.25        30
           8       0.00      0.00      0.00         2

    accuracy                           0.50       320
   macro avg       0.22      0.23      0.22       320
weighted avg       0.47      0.50      0.48       320



d:\Mesa R\วิชา อ.ต้น_Power_BI\DataMining\DataMining\environments\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Mesa R\วิชา อ.ต้น_Power_BI\DataMining\DataMining\environments\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Mesa R\วิชา อ.ต้น_Power_BI\DataMining\DataMining\environments\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control 