## การบ้าน library numpy 

นางสาวเมษา รักราษฎร์

In [ ]:
# import numpy 

import numpy as np

### 1 สร้างอาเรย์ 1 มิติ (1D array) สร้างอาเรย์ ขนาด 8 ที่มีค่าเป็น เลขคี่ จาก 1 ถึง 15 โดยใช้ np.arange()

In [3]:
import numpy as np

arr = np.arange(1, 16, 2)  # เริ่มจาก 1 ถึงไม่เกิน 16 โดยเพิ่มทีละ 2 (เลขคี่)
print(arr)

[ 1  3  5  7  9 11 13 15]


### 2 สร้างอาเรย์ 2 มิติ (2D array) สร้างอาเรย์ 3 แถว 5 คอลัมน์ ที่มีค่าเริ่มต้นทั้งหมดเป็น 9 โดยใช้ฟังก์ชันที่เหมาะสม (np.full() หรือวิธีอื่น)



In [4]:
arr = np.full((3, 5), 9)
print(arr)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


### 3 สร้างอาเรย์ 3 มิติ (3D array) สร้างอาเรย์ 2 × 3 × 4 ที่มีค่าเป็น 0 ทั้งหมด โดยใช้ np.zeros() และตรวจสอบ shape ของอาเรย์นั้น



In [9]:
arr = np.zeros((2, 3, 4))
print(arr)
print(arr.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)


### 4 การใช้ np.linspace() สร้างอาเรย์ที่มี 10 ค่า ซึ่งกระจายจาก 0 ถึง 5 แบบมีช่วงเท่ากันทุกตำแหน่ง

In [10]:
arr = np.linspace(0, 5, 10)
print(arr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


# แบบฝึกหัด: NumPy Indexing & Slicing default_array = np.array([1,2,3,4,5,6]) default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12]

### 1 เลือกสมาชิกตัวสุดท้าย ของ default_array โดยใช้ index โดยสร้างตัวแปรชื่อ last_item เพื่อรับค่า



In [13]:
import numpy as np

default_array = np.array([1, 2, 3, 4, 5, 6])

last_item = default_array[-1]
print("สมาชิกตัวสุดท้ายคือ:", last_item)

สมาชิกตัวสุดท้ายคือ: 6


### 2 เลือกสมาชิกตั้งแต่ตำแหน่งที่ 2 ถึง 4 (index 1–3) ของ default_array โดยสร้างตัวแปรชื่อ slice_2_to_4 เพื่อรับค่า



In [17]:
default_array = np.array([1, 2, 3, 4, 5, 6])

slice_2_to_4 = default_array[1:4]
print("สมาชิก index 1 - 3 คือ:", slice_2_to_4)

สมาชิก index 1 - 3 คือ: [2 3 4]


### 3 เลือกค่าทั้งหมดในคอลัมน์ที่ 2 ของ default_array_2d โดยสร้างตัวแปรชื่อ column_2 hint [:, 1]

In [19]:
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

column_2  = default_array_2d[:, 1]
print("คอลัมน์ที่ 2 คือ:", column_2)

คอลัมน์ที่ 2 คือ: [ 2  6 10]


### 4 เลือกค่าในแถวแรก 2 ตัวสุดท้าย ของ default_array_2d โดยสร้างตัวแปรชื่อ row1_last2 เพื่อรับค่า

In [21]:
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

row1_last2 = default_array_2d[0, -2:]
print("2 ตัวสุดท้ายของแถวแรก คือ:", row1_last2)

2 ตัวสุดท้ายของแถวแรก คือ: [3 4]


### 5 เลือกค่าที่อยู่มุมขวาล่าง (แถวสุดท้าย คอลัมน์สุดท้าย) ของ default_array_2d โดยสร้างตัวแปรชื่อ bottom_right เพื่อรับค่า

In [22]:
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

bottom_right = default_array_2d[-1, -1]
print("ค่าที่มุมขวาล่างคือ:", bottom_right)

ค่าที่มุมขวาล่างคือ: 12


# แบบฝึกหัด 3:

คำนวณ (x^2 + 2x) เมื่อ x = [1,2,3,4]




In [23]:
import numpy as np

x = np.array([1, 2, 3, 4])
result = x**2 + 2*x

print(result)

[ 3  8 15 24]
