## 1. Import numpy as np เรียกใช้งาน numpy

In [1]:
import numpy as np

In [ ]:
# Syntax creating Array
# array_name = np.array()

# 1 - dimensiona1 array 1,5,2,0 
arr_1d = np.array([ 1, 5, 2, 0 ])
# 2 - dimensional array  1,5,2,0  8,3,6,1  1,7,2,9
arr_2d = np.array([ [1,5,2,0], [8,3,6,1], [1,7,2,9] ])

# 3 - dimensional array 10, 15, 20, 25   30, 35, 40, 45   50, 55, 60, 65 
arr_3d = np.array([ [10, 15], 
                [ 20, 25], 
                
                [30, 35], 
                [40, 45],
                
                [50, 55], 
                [60, 65] ])

In [5]:
print(arr_1d)
print('----------------')
print(arr_2d)

[1 5 2 0]
----------------
[[1 5 2 0]
 [8 3 6 1]
 [1 7 2 9]]


In [6]:
print(arr_3d)

[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]]


In [7]:
default_array = np.array([1,2,3,4,5,6])
default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])

In [13]:
# สามตัวแรก จาก default_array
# default_array[ :3]

# ตีวที่ 4 เป็นต้นไป default_array
# default_array[3:]

# สามชืกใน row 2 columns 4  ใน default_array_2d
default_array_2d[1,3]

np.int64(8)

In [14]:
array_attribute = np.array([ [  1, 2, 3, 4 ], [  5, 6, 7, 8 ], [ 9, 10, 11, 12 ] ])

In [ ]:
# ตรวจสอบคุณสมบัติของ Array

# array_attribute.ndim ดูว่ามีกี่มิติ
array_attribute.ndim
# array_attribute.shape ดูว่ามีกี่แถว กี่คอลัมน์ (3,4)
array_attribute.shape
# array_attribute.size จำนวนสมาชิก
array_attribute.size
# array_attribute.dtype ตรวจสอบชนิดข้อมูล (dtype('int64'))
array_attribute.dtype

dtype('int64')

In [19]:
zero_2d_array = np.zeros(2)
one_1d_array = np.ones(5)
arang_array = np.arange(4)
step_arang_array= np.arange(2,9,2)  # start stop step 

In [20]:
# zero_2d_array
print(zero_2d_array)
# one_1d_array
print(one_1d_array)
# arang_array
print(arang_array)
# step_arang_array
print(step_arang_array)
print(one_1d_array)

[0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3]
[2 4 6 8]
[1. 1. 1. 1. 1.]


In [ ]:
array_sample = np.arange(20)

In [22]:
print(array_sample)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
# reshape สองแถว
array_sample.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [24]:
array_sample.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [26]:
# reshape(2,3)
array_sample.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])